# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: trzeci/emscripten:1.39.13
      environment:
        # Enable colors in term
        TERM: xterm
        # Avoid warnings by switching to noninteractive
        DEBIAN_FRONTEND: noninteractive
  working_directory: ~/

jobs:
  BUILD:
    <<: *defaults
    steps:
      - run: npm -v
      - run: yarn -v
      - run: git -v
      - checkout

# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
      - BUILD
